# 主播玩家名
host_playername: ""
# 主播的b站uid
bili_uid: 0
# 主播房间号
room_id: 0
# 是否开启调试模式
debug: false
# 涨粉全服公告消息
# 占位符: "{昵称}" "{涨粉数}" "{当前粉丝数}"
fans_grow_msg: "&6{昵称} &a新增了一名 &6{涨粉数} &a名随从! 当前随从数: &6{当前粉丝数}"
# 进入房间的公告信息
# 展示在玩家界面的底栏
enter_room_msg: "&d欢迎 &o&e{昵称} &d进入直播间"
# 刷怪设置
summon:
  # 怪物出生在哪个世界
  # 如果配置的世界不存在, 将使用默认世界 "world"
  world: world
  # 刷怪半径, 以主播(关注刷怪时)或在线玩家(弹幕召唤时)为圆心
  radius: 10
  # 关注刷怪
  follow:
    # 怪物类型, 随机抽取
    mobs:
      - ZOMBIE
      - CREEPER
      - SKELETON
      - ENDERMAN
  # 弹幕召唤
  danmu:
    # 公告消息格式
    start-msg-format: "&6{昵称} &a发起了 &e<{活动名}> &a弹幕召唤! &6快前往直播间为Ta助力吧!"
    running-msg-format: "&6{昵称} &a为 &e<{活动名}> &a召唤助力, 还剩 &e{剩余次数} &a次!"
    end-msg-format: "&e<{活动名}> &a召唤成功! 最后助攻: &6{昵称}!"
    # 召唤活动id, 可以任意修改为别的id, 不重复即可
    zombie-wave:
      # 展示给玩家的召唤活动名称
      activity-name: "僵尸军团"
      # 弹幕关键字, 只要弹幕包含其文字即可触发
      keyword: "僵尸军团"
      # 弹幕重复次数
      times: 10
      # 一个观众是否可重复多次
      # 尚未开发,不起作用
      repeat: true
      # 怪物, 暂时只能召唤一种, 可指定数量
      mob: "ZOMBIE*30"
      # 召唤冷却时间, 按秒计算
      cooldown: 20