# 主播玩家名
host_playername: ""
# 主播的b站uid
bili_uid: 0
# 主播房间号
room_id: 0
# 是否开启调试模式
debug: false
# 进入房间的公告信息
# 展示在玩家界面的底栏
# 清空文本可关闭此功能
enter_room_msg: "&d欢迎 &o&e{昵称} &d进入直播间"
# 刷怪设置
summon:
  # 刷怪半径, 以玩家为圆心
  radius: 10
# 涨粉公告消息及相关动作
follow:
  # 涨粉全服公告消息
  # 占位符: "{昵称}" "{涨粉数}" "{当前粉丝数}"
  msg: "&6{昵称} &a新增了一名 &6{涨粉数} &a名随从! 当前随从数: &6{当前粉丝数}"
  # 执行的动作
  do-action: "add-fans"
# 礼物互动
gifts:
  # 礼物名
  "辣条":
    # 提示消息,可根据实际效果定制
    # 如果带有"all:",则广播给所有玩家,否则只发给主播
    # 除非动作对所有玩家都有影响,尽量不使用"all:"防止刷屏
    # 占位符: "{昵称}" "{观众动作名}"(一般是"投喂") "{礼物名}" "{数量}" "{主播玩家名}"
    msg: "&a收到 &e{昵称} &a{观众动作名}的 &e{礼物名}*{数量}&f, &e{主播玩家名}&a全部吃下啦~"
    do-action: "gift-辣条"
    # 倍率开关. 若开启倍率, 则动作执行次数=礼物数
    # 例如回血操作(heal),若开启倍率,则最终回血量=礼物数*基础数值; 若不开启倍率, 则回血量=基础数值
    multiply: true
  "小心心":
    msg: "&a收到 &e{昵称} &a{观众动作名}&a的 &e{礼物名}*{数量}&f, &e{主播玩家名}&a元气up up~"
    do-action: "gift-小心心"
    multiply: true
  "凉了":
    msg: "&e{昵称} &c送上一曲&1凉凉&f, &e{主播玩家名} &c受到中毒伤害！"
    do-action: "gift-凉了"
    multiply: true
  "牛气爆竹":
    msg: "Test"
    do-action: "gift-牛气爆竹"
    multiply: false
# 弹幕互动活动
danmu:
  # 公告消息格式
  # "{限时}" 代表最长持续时间, 消息中会将秒转化为易读时间
  start-msg-format: "&6{昵称} &a发起了 &e<{活动名}> &a弹幕召唤! &e限时 &c{限时}! &6快前往直播间为Ta助力吧!"
  running-msg-format: "&6{昵称} &a为 &e<{活动名}> &a召唤助力, 还剩 &e{剩余次数} &a次!"
  end-msg-format: "&e<{活动名}> &a召唤成功! 最后助攻: &6{昵称}!"
  timeout-msg-format: "&c因超时&f, &e<{活动名}> &c召唤失败!"
  # 活动id, 可以任意修改为别的id, 不重复即可
  zombie-wave:
    # 展示给玩家的活动名称
    activity-name: "僵尸军团"
    # 弹幕关键字, 只要弹幕包含其文字即可触发
    keyword: "僵尸军团"
    # 活动最长持续时间,按秒计
    max-duration: 60
    # 弹幕重复次数
    times: 10
    # 一个观众是否可重复多次
    # 尚未开发,不起作用
    repeat: true
    do-action: "spawn-zombies"
    # 活动冷却时间, 按秒计算
    cooldown: 20

# 动作概念:一个动作可包含一个或多个操作.
# 操作配置的格式为: "操作名:数据"
# 支持的操作有:
# 1.回复生命值. 格式: "heal:基础数值"
# 2.回复饥饿值. 格式: "feed:基础数值"
# 3.给予状态效果. 格式: "effect:效果名:持续时间(秒):效果等级"
# 4.执行后台命令. 格式: "command:命令"
# 5.在主播附近刷怪. 格式: "spawn:怪物" 或 "spawn:怪物1|怪物2|...|怪物n",随机抽取一种
# 6.在所有在线玩家附近刷怪. 格式与上面的相同, 但操作名为"spawnforall"
# 7.治疗全体玩家. 操作名"healall",无附加数据
actions:
  gift-辣条:
    - 'command:say hello'
    - 'feed:1'
  gift-小心心:
    - 'heal:1'
  gift-凉了:
    - 'effect:POISON,5,1'
  gift-牛气爆竹:
    # 放烟花 暂未实现
    - 'firework:CREEPER'
  add-fans:
    # 不同怪物用"|"分开, 如果有多种怪物则从中随机挑选一种
    # 也可指定每种怪的数量,例如 "zombie*2|creeper*3"
    # 关注刷怪不需要指定数量, 插件会根据涨粉数刷相应数量的怪
    # 这是因为涨粉多少个,以下操作就会执行多少次
    - 'spawn:zombie,creeper,skeleton,enderman'
  spawn-zombies:
    - 'spawnforall:zombie*30'
  healall:
    # 治疗全体玩家
    - 'healall'